name: SonarQube (minimal)

on:
  push:
    branches: [ "canary" ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # http://ippublic:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sonar-nextjs
            -Dsonar.projectName=sonar-nextjs
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/coverage/**,**/*.min.js
